// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted attestation_plugin header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the attestation_plugin.edl file.
#include "attestation_plugin_u.h"

// Include plugin1's helpers
#include "../plugin1/plugin1.h"

oe_quote_customization_plugin_context_t* plugin1 = NULL;

bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--simulate") == 0)
        {
            fprintf(stdout, "Running in simulation mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;
            return true;
        }
    }
    return false;
}

// This is the function that the enclave will call back into to
// print a message.
void host_attestation_plugin(const void* evidence, size_t evidence_size)
{
    oe_result_t result = OE_FAILURE;
    oe_claim_element_t* claims = NULL;
    size_t claims_count = 0;
    uint8_t* user_data = NULL;
    size_t user_data_size = 0;

    fprintf(stdout, "Enclave called into host to print: attestation_plugin!\n");

    printf("Verifying attestation evidence with size=%zu\n", evidence_size);
    result = oe_verify_attestation_evidence(
        evidence,
        evidence_size,
        &claims,
        &claims_count,
        &user_data,
        &user_data_size);
    if (result != OE_OK)
    {
        fprintf(
            stdout,
            "host::oe_verify_attestation_evidence failed for "
            "evidence_format_uuid (1) with %s\n",
            oe_result_str(result));
        return;
    }

    fprintf(
        stdout,
        "host::oe_verify_attestation_evidence succeeded for "
        "evidence_format_uuid "
        "(1)\n");

    printf(
        "Returned user data was (size=%zu) %s\n",
        user_data_size,
        (const char*)user_data);

    oe_free_claims_list(claims, claims_count);
    free(user_data);
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    if (check_simulate_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    if (argc != 2)
    {
        fprintf(
            stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    // Register attestation plugins.
    plugin1 = create_plugin1();
    result = oe_register_attestation_plugin(plugin1, NULL, 0);
    if (result != OE_OK)
    {
        fprintf(
            stdout,
            "host::oe_register_attestation_plugin failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    // Create the enclave
    result = oe_create_attestation_plugin_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_attestation_plugin_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    // Call into the enclave
    result = enclave_attestation_plugin(enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_attestation_plugin failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    result = oe_unregister_attestation_plugin(plugin1);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling host::oe_unregister_plugin failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    ret = 0;

exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
